# Generated by Django 4.2.7 on 2026-06-25 15:32

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_english', models.CharField(blank=True, max_length=500)),
                ('title_japanese', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=600, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='anime/posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='anime/banners/')),
                ('poster_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('trailer_embed_id', models.CharField(blank=True, max_length=100)),
                ('anime_type', models.CharField(choices=[('tv', 'TV Series'), ('movie', 'Movie'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Special'), ('music', 'Music')], default='tv', max_length=20)),
                ('status', models.CharField(choices=[('airing', 'Currently Airing'), ('finished', 'Finished Airing'), ('upcoming', 'Not Yet Aired'), ('hiatus', 'On Hiatus'), ('discontinued', 'Discontinued')], default='finished', max_length=20)),
                ('source', models.CharField(choices=[('manga', 'Manga'), ('light_novel', 'Light Novel'), ('novel', 'Novel'), ('original', 'Original'), ('game', 'Game'), ('visual_novel', 'Visual Novel'), ('other', 'Other')], default='manga', max_length=20)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=10)),
                ('season_year', models.IntegerField(blank=True, null=True)),
                ('aired_from', models.DateField(blank=True, null=True)),
                ('aired_to', models.DateField(blank=True, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('scored_by', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('members', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
                ('mal_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('anilist_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_editor_pick', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', '-popularity'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#FF77C8', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='studios/')),
                ('website', models.URLField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('mal_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collections/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ManyToManyField(related_name='collections', to='anime.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='anime', to='anime.genre'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(blank=True, related_name='anime', to='anime.studio'),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='AnimeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('sequel', 'Sequel'), ('prequel', 'Prequel'), ('alternative_version', 'Alternative Version'), ('side_story', 'Side Story'), ('parent_story', 'Parent Story'), ('spin_off', 'Spin-off'), ('adaptation', 'Adaptation'), ('other', 'Other')], max_length=30)),
                ('from_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='anime.anime')),
                ('to_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='anime.anime')),
            ],
            options={
                'unique_together': {('from_anime', 'to_anime')},
            },
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['status'], name='anime_anime_status_6458e9_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['season', 'season_year'], name='anime_anime_season_7da247_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['is_trending'], name='anime_anime_is_tren_cb4a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['is_featured'], name='anime_anime_is_feat_f905ab_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['score'], name='anime_anime_score_fc3b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['popularity'], name='anime_anime_popular_f08e13_idx'),
        ),
    ]
