# Generated by Django 4.2.7 on 2026-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
