# Generated by Django 4.2.7 on 2026-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='trailer_embed_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
