# Generated by Django 4.2.7 on 2026-06-25 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_kanji', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('image_url', models.URLField(blank=True)),
                ('favorites', models.IntegerField(default=0)),
                ('mal_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-favorites'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='voice_actors/')),
                ('image_url', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('japanese', 'Japanese'), ('english', 'English'), ('korean', 'Korean'), ('spanish', 'Spanish'), ('french', 'French'), ('other', 'Other')], default='japanese', max_length=20)),
                ('favorites', models.IntegerField(default=0)),
                ('mal_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceActorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('voice_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.voiceactor')),
            ],
            options={
                'unique_together': {('voice_actor', 'character', 'anime')},
            },
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='characters',
            field=models.ManyToManyField(related_name='voice_actors', through='characters.VoiceActorRole', to='characters.character'),
        ),
        migrations.CreateModel(
            name='AnimeCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main'), ('supporting', 'Supporting'), ('background', 'Background')], default='supporting', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_characters', to='anime.anime')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_anime', to='characters.character')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('anime', 'character')},
            },
        ),
    ]
